# Generated by Django 5.0.4 on 2024-05-11 13:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

def agregar_bodegas(apps, schema_editor):
    Bodega = apps.get_model('apilemone', 'Bodega')
    Bodega.objects.create(nombre='Bodega Norte', descripcion='Ubicada en el norte.', activoactualmente=True, estado='A')
    Bodega.objects.create(nombre='Bodega Sur', descripcion='Ubicada en el sur.', activoactualmente=True, estado='A')
    
def agregar_tipos_de_vino(apps, schema_editor):
    TipoDeVino = apps.get_model('apilemone', 'TipoDeVino')
    TipoDeVino.objects.create(nombre='Orange')
    TipoDeVino.objects.create(nombre='Espumoso')
    TipoDeVino.objects.create(nombre='Joven')
    TipoDeVino.objects.create(nombre='Reserva')
    TipoDeVino.objects.create(nombre='Gran reserva')
    TipoDeVino.objects.create(nombre='Seco')
    
def agregar_categorias(apps, schema_editor):
    Categoria = apps.get_model('apilemone', 'Categoria')
    Categoria.objects.create(nombre='Tinto')
    Categoria.objects.create(nombre='Rosado')
    Categoria.objects.create(nombre='Dulce')
    Categoria.objects.create(nombre='Vermut')
    
def agregar_EstadoDeOrden(apps, schema_editor):
    EstadoDeOrden = apps.get_model('apilemone', 'EstadoDeOrden')
    EstadoDeOrden.objects.create(nombre='Nueva')
    EstadoDeOrden.objects.create(nombre='En proceso')
    EstadoDeOrden.objects.create(nombre='Finalizada')
    EstadoDeOrden.objects.create(nombre='Anulada')

def agregar_MedioDePago(apps, schema_editor):
    MedioDePago = apps.get_model('apilemone', 'MedioDePago')
    MedioDePago.objects.create(nombre='Efectivo')
    MedioDePago.objects.create(nombre='Crédito')
    MedioDePago.objects.create(nombre='Débito')
    MedioDePago.objects.create(nombre='Transferencia bancaria')
    
def agregar_TipoDePersona(apps, schema_editor):
    TipoDePersona = apps.get_model('apilemone', 'TipoDePersona')
    TipoDePersona.objects.create(nombre='Proveedor')
    TipoDePersona.objects.create(nombre='Cliente')
    
def agregar_TipoDeOperacion(apps, schema_editor):
    TipoDeOperacion = apps.get_model('apilemone', 'TipoDeOperacion')
    TipoDeOperacion.objects.create(nombre='Compra')
    TipoDeOperacion.objects.create(nombre='Venta')        

def agregar_TipoDeEnvio(apps, schema_editor):
    TipoDeEnvio = apps.get_model('apilemone', 'TipoDeEnvio')
    TipoDeEnvio.objects.create(nombre='Domicilio')
    TipoDeEnvio.objects.create(nombre='Retiro por depósito')   
    TipoDeEnvio.objects.create(nombre='Retiro por sucursal amiga')       
   
def agregar_PuntoClave(apps, schema_editor):
    PuntoClave = apps.get_model('apilemone', 'PuntoClave')
    PuntoClave.objects.create(nombre='Olor y sabor a madera')
    PuntoClave.objects.create(nombre='Equilibrio')   
    PuntoClave.objects.create(nombre='Profundidad y complejidad')   
    PuntoClave.objects.create(nombre='Persistencia')  
    
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('activoactualmente', models.BooleanField(default=True)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'bodega',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=1000)),
                ('activoactualmente', models.BooleanField(default=True)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='EstadoDeOrden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'EstadoDeOrden',
                'verbose_name_plural': 'EstadosDeOrden',
                'db_table': 'estadodeorden',
            },
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MedioDePago',
                'verbose_name_plural': 'MediosDePago',
                'db_table': 'mediodepago',
            },
        ),
        migrations.CreateModel(
            name='PuntoClave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'puntoclave',
                'verbose_name_plural': 'PuntosClaves',
                'db_table': 'puntoclave',
            },
        ),
        migrations.CreateModel(
            name='TipoDeEnvio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoDeEnvio',
                'verbose_name_plural': 'TiposDeEnvio',
                'db_table': 'tipodeenvio',
            },
        ),
        migrations.CreateModel(
            name='TipoDeOperacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoDeOperacion',
                'verbose_name_plural': 'TiposDeOperacion',
                'db_table': 'tipodeoperacion',
            },
        ),
        migrations.CreateModel(
            name='TipoDePersona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'TipoDePersona',
                'verbose_name_plural': 'TiposDePersona',
                'db_table': 'tipodePersona',
            },
        ),
        migrations.CreateModel(
            name='TipoDeVino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'tipodevino',
                'verbose_name_plural': 'TiposDeVino',
                'db_table': 'tipodevino',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('activoactualmente', models.BooleanField(default=True)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=django.utils.timezone.now)),
                ('fehamodificacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('usuarioalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_usuarioalta', to=settings.AUTH_USER_MODEL)),
                ('usuariomodificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_usuariomodificacion', to=settings.AUTH_USER_MODEL)),
                ('tipodepersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodepersona')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nrodeorden', models.IntegerField()),
                ('nrodetransaccion', models.IntegerField()),
                ('importeneto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importeiva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importetotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('estadodeorden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.estadodeorden')),
                ('mediodepago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.mediodepago')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.persona')),
                ('tipodeenvio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodeenvio')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('inventariominimo', models.IntegerField(default=20)),
                ('preciodecosto', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('preciodeventa', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('activoactualmente', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, max_length=150)),
                ('porcentajedealcohol', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=django.utils.timezone.now)),
                ('fehamodificacion', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('bodega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.bodega')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.categoria')),
                ('usuarioalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_usuarioalta', to=settings.AUTH_USER_MODEL)),
                ('usuariomodificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_usuariomodificacion', to=settings.AUTH_USER_MODEL)),
                ('tipodevino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodevino')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.CharField(max_length=250, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.producto')),
            ],
            options={
                'verbose_name': 'Orden_Detalle',
                'verbose_name_plural': 'Ordenes_Detalle',
                'db_table': 'orden_detalle',
            },
        ),
        migrations.CreateModel(
            name='ProductoDestacado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechadesde', models.DateField(default=django.utils.timezone.now)),
                ('fechahasta', models.DateField(default=django.utils.timezone.now)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.producto')),
            ],
            options={
                'verbose_name': 'ProductoDestacado',
                'verbose_name_plural': 'ProductosDestacados',
                'db_table': 'productodestacado',
            },
        ),
        migrations.CreateModel(
            name='PuntoClavePorProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.producto')),
                ('puntoclave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.puntoclave')),
            ],
            options={
                'verbose_name': 'puntoclaveporproducto',
                'verbose_name_plural': 'PuntosClavesPorProducto',
                'db_table': 'puntoclaveporproducto',
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.persona')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.producto')),
                ('tipodeoperacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodeoperacion')),
            ],
            options={
                'verbose_name': 'Operacion',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'operacion',
            },
        ),
        migrations.RunPython(agregar_bodegas),
        migrations.RunPython(agregar_categorias),
        migrations.RunPython(agregar_EstadoDeOrden),
        migrations.RunPython(agregar_MedioDePago),
        migrations.RunPython(agregar_PuntoClave),
        migrations.RunPython(agregar_TipoDePersona),
        migrations.RunPython(agregar_TipoDeEnvio),
        migrations.RunPython(agregar_tipos_de_vino),
        migrations.RunPython(agregar_TipoDeOperacion)
    ]
