# Generated by Django 5.0.4 on 2024-05-05 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilemone', '0005_estadodeorden_mediodepago_orden_tipodeenvio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tipodeoperacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodeoperacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='mediodepago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.mediodepago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipodeenvio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodeenvio'),
        ),
        migrations.AlterField(
            model_name='ordendetalle',
            name='observaciones',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
