# Generated by Django 5.0.4 on 2024-05-05 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilemone', '0006_orden_tipodeoperacion_alter_orden_mediodepago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='mediodepago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.mediodepago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipodeenvio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apilemone.tipodeenvio'),
        ),
    ]
