# Generated by Django 5.0.4 on 2024-05-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apilemone', '0007_alter_orden_mediodepago_alter_orden_tipodeenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='tipodeoperacion',
        ),
    ]
