# Generated by Django 5.0.4 on 2024-05-07 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apilemone', '0008_remove_orden_tipodeoperacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDestado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechadesde', models.DateField(default=django.utils.timezone.now)),
                ('fechahasta', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('fechaalta', models.DateField(default=django.utils.timezone.now)),
                ('fechamodificacion', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilemone.producto')),
                ('usuarioalta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productodestacado_usuarioalta', to=settings.AUTH_USER_MODEL)),
                ('usuariomodificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productodestacado_usuariomodificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductoDestacado',
                'verbose_name_plural': 'ProductosDestacados',
                'db_table': 'productodestacado',
            },
        ),
    ]
